spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://db-prod:5432/accountdb
    username: prod_user
    password: SENHA_AQUI

server:
  port: 8081

myapp:
  greeting: "Olá PROD - Account Service"
