spring:
  application:
    name: account-service

server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:accountdb-dev
    username: sa
    password: devpass

myapp:
  greeting: "Olá DEV - Account Service"
