spring:
  application:
    name: account-service

  datasource:
    url: jdbc:h2:mem:accountdb-dev
    username: sa
    password: devpass

server:
  port: 8081

myapp:
  greeting: "Olá DEV - Account Service"
